import _ from 'lodash';

const inventory = [
  {
    id: 1,
    category: 'חד פעמי',
    name: 'צלחות גדולות',
    description: '1/100 קשיח',
    price: 20,
  },
  {
    id: 2,
    category: 'חד פעמי',
    name: 'צלחות גדולות',
    description: '1/50 פשוט',
    price: 5.75,
  },
  {
    id: 3,
    category: 'חד פעמי',
    name: 'צלחות גדולות',
    description: '1/25 קשיח',
    price: 7,
  },
  {
    id: 4,
    category: 'חד פעמי',
    name: 'צלחות קטנות',
    description: '1/100 קשיח',
    price: 17.5,
  },
  {
    id: 5,
    category: 'חד פעמי',
    name: 'צלחות קטנות',
    description: '1/50 פשוט',
    price: 3.8,
  },
  {
    id: 6,
    category: 'חד פעמי',
    name: 'צלחות קטנות',
    description: '1/25 קשיח',
    price: 4,
  },
  {
    id: 7,
    category: 'חד פעמי',
    name: 'מזלג',
    description: '1/100 פשוט',
    price: 4.6,
  },
  {
    id: 8,
    category: 'חד פעמי',
    name: 'סכין',
    description: '1/100 פשוט',
    price: 4.6,
  },
  {
    id: 9,
    category: 'חד פעמי',
    name: 'כף',
    description: '1/100 פשוט',
    price: 4.6,
  },
  {
    id: 10,
    category: 'חד פעמי',
    name: 'כפית',
    description: '1/100 פשוט',
    price: 3.7,
  },
  {
    id: 11,
    category: 'חד פעמי',
    name: 'מזלג',
    description: '1/50 קשיח',
    price: 6.9,
  },
  {
    id: 12,
    category: 'חד פעמי',
    name: 'סכין',
    description: '1/50 קשיח',
    price: 6.9,
  },
  {
    id: 13,
    category: 'חד פעמי',
    name: 'כף',
    description: '1/50 קשיח',
    price: 6.9,
  },
  {
    id: 14,
    category: 'חד פעמי',
    name: 'כפית',
    description: '1/50 קשיח',
    price: 4.2,
  },
  {
    id: 15,
    category: 'חד פעמי',
    name: 'מזלג מוכסף',
    description: '1/20.',
    price: 4,
  },
  {
    id: 16,
    category: 'חד פעמי',
    name: 'תבנית אינגליש',
    description: '',
    price: 0.35,
  },
  {
    id: 17,
    category: 'חד פעמי',
    name: 'תבנית בינוני',
    description: '',
    price: 0.9,
  },
  {
    id: 18,
    category: 'חד פעמי',
    name: 'תבנית גדולה',
    description: '',
    price: 2.1,
  },
  {
    id: 19,
    category: 'חד פעמי',
    name: 'תבנית עגולה עמוקה',
    description: '',
    price: 0.93,
  },
  {
    id: 20,
    category: 'חד פעמי',
    name: 'תבנית עגולה קטנה',
    description: '',
    price: 0.35,
  },
  {
    id: 21,
    category: 'חד פעמי',
    name: 'קערות הגשה',
    description: '1/10.',
    price: 12.2,
  },
  {
    id: 22,
    category: 'חד פעמי',
    name: 'קערות הגשה',
    description: '1/25.',
    price: 15,
  },
  {
    id: 23,
    category: 'חד פעמי',
    name: 'ליפתנית',
    description: '1/25.',
    price: 2.2,
  },
  {
    id: 24,
    category: 'חד פעמי',
    name: 'ליפתנית אובלי',
    description: '',
    price: 3.4,
  },
  {
    id: 25,
    category: 'חד פעמי',
    name: 'מפת אל-בד',
    description: '25 מטר',
    price: 22.8,
  },
  {
    id: 26,
    category: 'חד פעמי',
    name: 'מפת אל-בד',
    description: '100 מטר',
    price: 96,
  },
  {
    id: 27,
    category: 'חד פעמי',
    name: 'קעריות מרק',
    description: '1/25.',
    price: 4.2,
  },
  {
    id: 28,
    category: 'חד פעמי',
    name: 'קעריות מרק',
    description: '1/100.',
    price: 11,
  },
  {
    id: 29,
    category: 'חד פעמי',
    name: 'כוסות קר',
    description: '1/100 פשוט',
    price: 3.3,
  },
  {
    id: 30,
    category: 'חד פעמי',
    name: 'כוסות קר',
    description: '1/100 קשיח',
    price: 4.1,
  },
  {
    id: 31,
    category: 'חד פעמי',
    name: 'כוסות קר',
    description: '1/50 מעוטר',
    price: 8,
  },
  {
    id: 32,
    category: 'חד פעמי',
    name: 'כוסות חם',
    description: '1/50 8אינץ',
    price: 5.5,
  },
  {
    id: 33,
    category: 'חד פעמי',
    name: 'כוסות חם',
    description: '1/50 10אינץ',
    price: 8.8,
  },
  {
    id: 34,
    category: 'חד פעמי',
    name: 'כוסות חם',
    description: '1/50 12אינץ',
    price: 10.4,
  },
  {
    id: 35,
    category: 'חד פעמי',
    name: 'כוסות יין',
    description: '1/50.',
    price: 1.75,
  },
  {
    id: 36,
    category: 'חד פעמי',
    name: 'כף הגשה',
    description: '1/2 זוגי',
    price: 3,
  },
  {
    id: 37,
    category: 'חד פעמי',
    name: 'מפיות',
    description: '1/100.',
    price: 3.9,
  },
  {
    id: 38,
    category: 'חד פעמי',
    name: 'מפיות',
    description: '1/160',
    price: 5.1,
  },
  {
    id: 39,
    category: 'חד פעמי',
    name: 'נייר אפיה',
    description: '1/50.',
    price: 8.5,
  },
  {
    id: 40,
    category: 'חד פעמי',
    name: 'ניילון נצמד מוסדי',
    description: '150 מטר',
    price: 22,
  },
  {
    id: 41,
    category: 'חד פעמי',
    name: 'ניילון נצמד מוסדי',
    description: '300 מטר',
    price: 39,
  },
  {
    id: 42,
    category: 'חד פעמי',
    name: 'אלומניום כוכב',
    description: '',
    price: 24.5,
  },
  {
    id: 43,
    category: 'חד פעמי',
    name: 'אשפתון',
    description: 'שחור',
    price: 10.8,
  },
  {
    id: 44,
    category: 'חד פעמי',
    name: 'אשפתון',
    description: 'כחול',
    price: 6.8,
  },
  {
    id: 45,
    category: 'חד פעמי',
    name: 'אשפתון',
    description: 'גליל קטן',
    price: 7.9,
  },
  {
    id: 46,
    category: 'חד פעמי',
    name: 'כרית יפנית',
    description: 'זוגי',
    price: 1.77,
  },
  {
    id: 47,
    category: 'חד פעמי',
    name: 'כרית יפנית',
    description: 'שישיה',
    price: 6.4,
  },
  {
    id: 48,
    category: 'חד פעמי',
    name: 'סקוטש',
    description: '',
    price: 1.75,
  },
  {
    id: 49,
    category: 'חד פעמי',
    name: 'מגבות קונטרול',
    description: '1/6.',
    price: 53.8,
  },
  {
    id: 50,
    category: 'חד פעמי',
    name: 'נייר טואלט טאצ',
    description: '1/48.',
    price: 36,
  },
  {
    id: 51,
    category: 'חד פעמי',
    name: "נייר טואלט ג'מבו",
    description: '1/12.',
    price: 51,
  },
  {
    id: 52,
    category: 'חד פעמי',
    name: 'מגבות מטבח שניב',
    description: '1/6 פשוט',
    price: 24,
  },
  {
    id: 53,
    category: 'חד פעמי',
    name: 'סדין רפואי',
    description: '1/3.',
    price: '',
  },
  {
    id: 54,
    category: 'חד פעמי',
    name: 'מגבונים לחים',
    description: '',
    price: 2.8,
  },
  {
    id: 55,
    category: 'חד פעמי',
    name: 'סבון אסלה שלישיה',
    description: '',
    price: '',
  },
  {
    id: 56,
    category: 'חד פעמי',
    name: 'מיכל +מכסה',
    description: '1 ליטר',
    price: 1,
  },
  {
    id: 57,
    category: 'חד פעמי',
    name: 'מיכל +מכסה',
    description: '2 ליטר',
    price: 1.2,
  },
  {
    id: 58,
    category: 'חד פעמי',
    name: 'מיכל +מכסה',
    description: '4.5 ליטר',
    price: 3.3,
  },
  {
    id: 59,
    category: 'חד פעמי',
    name: 'דלי',
    description: '15 ליטר',
    price: 10,
  },
  {
    id: 60,
    category: 'מוצרי נקיון והיגיינה',
    name: 'אקונומיקה',
    description: '4 ליטר',
    price: '',
  },
  {
    id: 61,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון ידיים',
    description: '4 ליטר',
    price: 16,
  },
  {
    id: 62,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון כלים 24%',
    description: '4 ליטר',
    price: 22,
  },
  {
    id: 63,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ניקוי רצפות',
    description: '4 ליטר',
    price: '',
  },
  {
    id: 64,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ניקוי חלונות',
    description: '4 ליטר',
    price: 15,
  },
  {
    id: 65,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מסיר שומנים',
    description: '4 ליטר',
    price: 29,
  },
  {
    id: 66,
    category: 'מוצרי נקיון והיגיינה',
    name: "ג'ל כביסה",
    description: '4 ליטר',
    price: '',
  },
  {
    id: 67,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מרכך כביסה',
    description: '4 ליטר',
    price: '',
  },
  {
    id: 68,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סחבה לחה',
    description: 'דלי',
    price: 24,
  },
  {
    id: 69,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטלית ניקוי',
    description: 'דלי',
    price: 20,
  },
  {
    id: 70,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטלית חיטוי 99.9%',
    description: 'דלי',
    price: 30,
  },
  {
    id: 71,
    category: 'מוצרי נקיון והיגיינה',
    name: 'נוזל רצפות פנטסטיק',
    description: '3 קילו',
    price: '',
  },
  {
    id: 72,
    category: 'מוצרי נקיון והיגיינה',
    name: 'משחת כלים דלי',
    description: '3.5 קילו',
    price: 21,
  },
  {
    id: 73,
    category: 'מוצרי נקיון והיגיינה',
    name: 'עוצם- חומצה',
    description: '4 ליטר',
    price: 25,
  },
  {
    id: 74,
    category: 'מוצרי נקיון והיגיינה',
    name: "אלכוהול ג'ל",
    description: '500 מ"ל',
    price: 20,
  },
  {
    id: 75,
    category: 'מוצרי נקיון והיגיינה',
    name: "אלכוהול ג'ל",
    description: '4 ליטר',
    price: 91,
  },
  {
    id: 76,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ברזלית ננס',
    description: '',
    price: 3,
  },
  {
    id: 77,
    category: 'מוצרי נקיון והיגיינה',
    name: 'צמר פלדה',
    description: '400 גרם',
    price: 10,
  },
  {
    id: 78,
    category: 'מוצרי נקיון והיגיינה',
    name: 'שקית ניילון גופיה',
    description: "100 יח' קטן",
    price: 8,
  },
  {
    id: 79,
    category: 'מוצרי נקיון והיגיינה',
    name: 'שקית ניילון גופיה',
    description: "60 יח' גדול",
    price: 9.9,
  },
  {
    id: 80,
    category: 'מוצרי נקיון והיגיינה',
    name: 'יאה+מקל',
    description: '',
    price: 14,
  },
  {
    id: 81,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטאטא סוס',
    description: '',
    price: 16,
  },
  {
    id: 82,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטאטא כביש',
    description: '',
    price: 23,
  },
  {
    id: 83,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטאטא רגיל',
    description: '',
    price: 5,
  },
  {
    id: 84,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מגב גדול',
    description: '',
    price: 18,
  },
  {
    id: 85,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מגב עם תופסן',
    description: '',
    price: 18,
  },
  {
    id: 86,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מגב חד להב',
    description: '',
    price: 13,
  },
  {
    id: 87,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מגבות מטבח פשוט',
    description: '1/6.',
    price: 8.7,
  },
  {
    id: 88,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מגבות צץ רץ',
    description: "400 יח'",
    price: 51,
  },
  {
    id: 89,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטלית',
    description: 'פשוט',
    price: 0.5,
  },
  {
    id: 90,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מבשם אוויר למתקן',
    description: '',
    price: '',
  },
  {
    id: 91,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סחבה מיקרופייבר',
    description: 'שלישיה',
    price: 15,
  },
  {
    id: 92,
    category: 'מוצרי נקיון והיגיינה',
    name: 'כפפות',
    description: '',
    price: 25,
  },
  {
    id: 93,
    category: 'מוצרי נקיון והיגיינה',
    name: 'כפפות ניילון',
    description: '',
    price: 5,
  },
  {
    id: 94,
    category: 'מוצרי נקיון והיגיינה',
    name: 'כפפות נטול טלק',
    description: '',
    price: 37,
  },
  {
    id: 95,
    category: 'מוצרי נקיון והיגיינה',
    name: 'כפפות משק',
    description: '',
    price: 4,
  },
  {
    id: 96,
    category: 'מוצרי נקיון והיגיינה',
    name: 'כפפות תנור',
    description: '',
    price: 40,
  },
  {
    id: 97,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ספריי לחלונות',
    description: '',
    price: 6.5,
  },
  {
    id: 98,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ממחטות אף',
    description: 'טאצ 1/5',
    price: 12,
  },
  {
    id: 99,
    category: 'מוצרי נקיון והיגיינה',
    name: 'שקיות שירות',
    description: '20/30',
    price: 15,
  },
  {
    id: 100,
    category: 'מוצרי נקיון והיגיינה',
    name: 'תרסיס לניקוי נירוסטה',
    description: '500 מ"ל',
    price: '',
  },
  {
    id: 101,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ספרי גוקים',
    description: '300 מ"ל',
    price: '',
  },
  {
    id: 102,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ספרים נמלים',
    description: '300 מ"ל',
    price: '',
  },
  {
    id: 103,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ספוג פלא',
    description: '',
    price: 6,
  },
  {
    id: 104,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון נוזלי שלישיה',
    description: '500 מ"ל',
    price: '',
  },
  {
    id: 105,
    category: 'מוצרי נקיון והיגיינה',
    name: 'נוזל כלים אונו',
    description: '1.5 ליטר',
    price: 10,
  },
  {
    id: 106,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון נוזלי ידיים קלאסיק',
    description: '1 ליטר',
    price: 7.9,
  },
  {
    id: 107,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון כלי ויש',
    description: '750 מ"ל',
    price: 5,
  },
  {
    id: 108,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון כלי פרי',
    description: '750 מ"ל',
    price: '',
  },
  {
    id: 109,
    category: 'מוצרי נקיון והיגיינה',
    name: 'סבון כלים סוד',
    description: '650 מ"ל',
    price: 5.7,
  },
  {
    id: 110,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מטליות לחות מילוי לדלי',
    description: '',
    price: 17.4,
  },
  {
    id: 111,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מסכה',
    description: "50 יח'",
    price: '',
  },
  {
    id: 112,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מברשת שיניים',
    description: "חבילה 4 יח'",
    price: '',
  },
  {
    id: 113,
    category: 'מוצרי נקיון והיגיינה',
    name: 'משחת שיניים קולגט',
    description: '',
    price: '',
  },
  {
    id: 114,
    category: 'מוצרי נקיון והיגיינה',
    name: 'הוואי- שמפו',
    description: '',
    price: '',
  },
  {
    id: 115,
    category: 'מוצרי נקיון והיגיינה',
    name: 'הוואי-מרכך',
    description: '',
    price: '',
  },
  {
    id: 116,
    category: 'מוצרי נקיון והיגיינה',
    name: 'פינוק-שמפו',
    description: '',
    price: '',
  },
  {
    id: 117,
    category: 'מוצרי נקיון והיגיינה',
    name: 'פינוק - מרכך',
    description: '',
    price: '',
  },
  {
    id: 118,
    category: 'מוצרי נקיון והיגיינה',
    name: 'פינוק - תחליב רחצה',
    description: '',
    price: '',
  },
  {
    id: 119,
    category: 'מוצרי נקיון והיגיינה',
    name: 'דאב- שמפו+ מרכך',
    description: '',
    price: '',
  },
  {
    id: 120,
    category: 'מוצרי נקיון והיגיינה',
    name: 'דאב- שמפו',
    description: '',
    price: '',
  },
  {
    id: 121,
    category: 'מוצרי נקיון והיגיינה',
    name: 'אלביב - שמפו+ מרכך',
    description: '',
    price: '',
  },
  {
    id: 122,
    category: 'מוצרי נקיון והיגיינה',
    name: 'נקה 7- תחליב רחצה',
    description: '',
    price: '',
  },
  {
    id: 123,
    category: 'מוצרי נקיון והיגיינה',
    name: 'צמרוני אוזנים פלסטיק',
    description: "200 יח'",
    price: 3.5,
  },
  {
    id: 124,
    category: 'מוצרי נקיון והיגיינה',
    name: 'תרסיס חיטוי טאצ',
    description: '',
    price: 11.5,
  },
  {
    id: 125,
    category: 'מוצרי נקיון והיגיינה',
    name: 'ספרי חיטוי',
    description: '',
    price: 15.9,
  },
  {
    id: 126,
    category: 'מוצרי נקיון והיגיינה',
    name: 'מכסה לגביע',
    description: '',
    price: 13,
  },
  {
    id: 127,
    category: 'מוצרי נקיון והיגיינה',
    name: 'גביע',
    description: '125 גרם',
    price: 15,
  },
  {
    id: 128,
    category: 'מוצרי נקיון והיגיינה',
    name: 'שקיות סנדוויץ',
    description: "100 יח'",
    price: 2.1,
  },
  {
    id: 129,
    category: 'שימורים',
    name: 'טונה',
    description: '1 קילו',
    price: 26,
  },
  {
    id: 130,
    category: 'שימורים',
    name: 'טונה פילטונה',
    description: 'רביעיה בשמן',
    price: '',
  },
  {
    id: 131,
    category: 'שימורים',
    name: 'טונה פילטונה',
    description: '414 גרם',
    price: 13,
  },
  {
    id: 132,
    category: 'שימורים',
    name: 'טונה פילטונה',
    description: 'רביעיה במים',
    price: 27,
  },
  {
    id: 133,
    category: 'שימורים',
    name: 'טונה פוסידון',
    description: '110 גרם',
    price: 5,
  },
  {
    id: 134,
    category: 'שימורים',
    name: 'סטארקיסט',
    description: '500 גרם',
    price: '',
  },
  {
    id: 135,
    category: 'שימורים',
    name: 'זיתים חרוזית',
    description: '3 ליטר',
    price: 36,
  },
  {
    id: 136,
    category: 'שימורים',
    name: 'זיתים חרוזית',
    description: 'בלי גרעינים 500 גרם',
    price: 7.9,
  },
  {
    id: 137,
    category: 'שימורים',
    name: 'זיתים',
    description: 'עם גרעינים 500 גרם',
    price: 7.6,
  },
  {
    id: 138,
    category: 'שימורים',
    name: 'מלפפון במלח/בחומץ',
    description: '7/9.',
    price: 5.73,
  },
  {
    id: 139,
    category: 'שימורים',
    name: 'מלפפון במלח/בחומץ',
    description: '10/12 בית השיטה',
    price: 7.4,
  },
  {
    id: 140,
    category: 'שימורים',
    name: 'מלפפון במלח/בחומץ',
    description: '13/17 בני דרום',
    price: 7.3,
  },
  {
    id: 141,
    category: 'שימורים',
    name: 'מלפפון במלח/בחומץ',
    description: '3 ליטר',
    price: 21.9,
  },
  {
    id: 142,
    category: 'שימורים',
    name: 'רסק עגבניות',
    description: 'פח 500 גרם',
    price: 5.1,
  },
  {
    id: 143,
    category: 'שימורים',
    name: 'רסק עגבניות',
    description: '280 גרם',
    price: 3.6,
  },
  {
    id: 144,
    category: 'שימורים',
    name: 'רסק עגבניות',
    description: '100 גרם',
    price: 1.6,
  },
  {
    id: 145,
    category: 'שימורים',
    name: 'תירס במים',
    description: '500 גרם',
    price: '',
  },
  {
    id: 146,
    category: 'שימורים',
    name: 'תירס ואקום',
    description: '500 גרם',
    price: '',
  },
  {
    id: 147,
    category: 'שימורים',
    name: 'תירס קל',
    description: '500 גרם ללא סוכר',
    price: 6,
  },
  {
    id: 148,
    category: 'שימורים',
    name: 'חומוס פרי גליל',
    description: '500 גרם',
    price: 4.8,
  },
  {
    id: 149,
    category: 'שימורים',
    name: 'אפונה פרי גליל',
    description: '500 גרם',
    price: 5.3,
  },
  {
    id: 150,
    category: 'שימורים',
    name: 'אפונה וגזר',
    description: '500 גרם',
    price: 5.3,
  },
  {
    id: 151,
    category: 'שימורים',
    name: 'פטריות חתוכות שלישיה',
    description: '500 גרם',
    price: '',
  },
  {
    id: 152,
    category: 'שימורים',
    name: 'שעועית אפויה ברוטב',
    description: '500 גרם',
    price: 5.4,
  },
  {
    id: 153,
    category: 'שימורים',
    name: 'דגיר',
    description: '',
    price: 4.4,
  },
  {
    id: 154,
    category: 'שימורים',
    name: 'חמין',
    description: '500 גרם ויטה',
    price: 6.9,
  },
  {
    id: 155,
    category: 'ממרחים',
    name: 'ממרח תמרים',
    description: '400 גרם',
    price: 5.9,
  },
  {
    id: 156,
    category: 'ממרחים',
    name: 'חמאת בוטנים',
    description: '400 גרם',
    price: '',
  },
  {
    id: 157,
    category: 'ממרחים',
    name: 'ממרח חלבה',
    description: '400 גרם',
    price: 10.4,
  },
  {
    id: 158,
    category: 'ממרחים',
    name: 'ממרחי טחינה עם סילאן',
    description: '400 גרם',
    price: 10.4,
  },
  {
    id: 159,
    category: 'ממרחים',
    name: 'ממרח שומשום קוקוס',
    description: '400 גרם',
    price: 10.4,
  },
  {
    id: 160,
    category: 'ממרחים',
    name: 'נוטלה',
    description: '400 גרם',
    price: 13.4,
  },
  {
    id: 161,
    category: 'ממרחים',
    name: 'נוטלה',
    description: '750 גרם',
    price: 25,
  },
  {
    id: 162,
    category: 'ממרחים',
    name: 'דבש יד מרדכי',
    description: '350 גרם',
    price: '',
  },
  {
    id: 163,
    category: 'ממרחים',
    name: 'דבש צרופה',
    description: '350 גרם',
    price: 14.7,
  },
  {
    id: 164,
    category: 'ממרחים',
    name: 'שוקולד שחר',
    description: '400 גרם',
    price: '',
  },
  {
    id: 165,
    category: 'קיטניות',
    name: 'חומוס',
    description: '500 גרם',
    price: '',
  },
  {
    id: 166,
    category: 'קיטניות',
    name: 'אפונה',
    description: '500 גרם',
    price: '',
  },
  {
    id: 167,
    category: 'קיטניות',
    name: 'עדש ירוק',
    description: '500 גרם',
    price: '',
  },
  {
    id: 168,
    category: 'קיטניות',
    name: 'שעועית לבנה',
    description: '500 גרם',
    price: '',
  },
  {
    id: 169,
    category: 'קיטניות',
    name: 'גריסים',
    description: '500 גרם',
    price: '',
  },
  {
    id: 170,
    category: 'קיטניות',
    name: 'תירס פופקורן',
    description: '500 גרם',
    price: '',
  },
  {
    id: 171,
    category: 'קיטניות',
    name: 'אורז פרסי',
    description: '1 קילו',
    price: '',
  },
  {
    id: 172,
    category: 'קיטניות',
    name: 'אורז בסמטי',
    description: '1 קילו',
    price: '',
  },
  {
    id: 173,
    category: 'קיטניות',
    name: 'אורז עגול',
    description: '1 קילו',
    price: '',
  },
  {
    id: 174,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סודה לשתיה',
    description: '1 קילו',
    price: 6.9,
  },
  {
    id: 175,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סודה לשתיה',
    description: '50 גרם',
    price: 1.4,
  },
  {
    id: 176,
    category: 'תבלינים ומוצרי יסוד',
    name: 'קנמון',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 177,
    category: 'תבלינים ומוצרי יסוד',
    name: 'כמון',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 178,
    category: 'תבלינים ומוצרי יסוד',
    name: 'פלפל שחור',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 179,
    category: 'תבלינים ומוצרי יסוד',
    name: 'פלפל שחור',
    description: '1 קילו',
    price: '',
  },
  {
    id: 180,
    category: 'תבלינים ומוצרי יסוד',
    name: 'כורכום',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 181,
    category: 'תבלינים ומוצרי יסוד',
    name: 'פפריקה מתוקה',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 182,
    category: 'תבלינים ומוצרי יסוד',
    name: 'פפריקה מתוקה',
    description: '1 קילו',
    price: '',
  },
  {
    id: 183,
    category: 'תבלינים ומוצרי יסוד',
    name: 'גריל עוף',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 184,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח לימון',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 185,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח לימון',
    description: '1 קילו',
    price: 10.5,
  },
  {
    id: 186,
    category: 'תבלינים ומוצרי יסוד',
    name: 'אבקת שום',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 187,
    category: 'תבלינים ומוצרי יסוד',
    name: 'שום גבישי',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 188,
    category: 'תבלינים ומוצרי יסוד',
    name: 'זעתר',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 189,
    category: 'תבלינים ומוצרי יסוד',
    name: 'בזיליקם',
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 190,
    category: 'תבלינים ומוצרי יסוד',
    name: "חוויג' מרק",
    description: '80 גרם',
    price: 3.7,
  },
  {
    id: 191,
    category: 'תבלינים ומוצרי יסוד',
    name: 'שמן קנולה',
    description: '1 ליטר',
    price: 7.3,
  },
  {
    id: 192,
    category: 'תבלינים ומוצרי יסוד',
    name: 'שמן זית כתית',
    description: '750 מ"ל',
    price: 31,
  },
  {
    id: 193,
    category: 'תבלינים ומוצרי יסוד',
    name: 'ביצים',
    description: '',
    price: '',
  },
  {
    id: 194,
    category: 'תבלינים ומוצרי יסוד',
    name: 'קמח כחול',
    description: '1 קילו',
    price: 3.3,
  },
  {
    id: 195,
    category: 'תבלינים ומוצרי יסוד',
    name: 'קמח דגן',
    description: '1 קילו',
    price: 4.5,
  },
  {
    id: 196,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סולת',
    description: '1 קילו',
    price: 4.5,
  },
  {
    id: 197,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח',
    description: '1 קילו',
    price: 1.79,
  },
  {
    id: 198,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכר',
    description: '1 קילו',
    price: 3.5,
  },
  {
    id: 199,
    category: 'תבלינים ומוצרי יסוד',
    name: 'קמח תופח',
    description: '1 קילו',
    price: '',
  },
  {
    id: 200,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכר צנצנת',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 201,
    category: 'תבלינים ומוצרי יסוד',
    name: 'קמח מנופה',
    description: '1 ליטר',
    price: 5.2,
  },
  {
    id: 202,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח ים',
    description: '250 גרם',
    price: 5.4,
  },
  {
    id: 203,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח ים',
    description: '500 גרם',
    price: 6.4,
  },
  {
    id: 204,
    category: 'תבלינים ומוצרי יסוד',
    name: 'שמרים יבשים',
    description: '500 גרם',
    price: 9.5,
  },
  {
    id: 205,
    category: 'תבלינים ומוצרי יסוד',
    name: 'שמרים יבשים',
    description: '125 גרם',
    price: 4,
  },
  {
    id: 206,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכר אישי',
    description: "1000 יח'",
    price: '',
  },
  {
    id: 207,
    category: 'תבלינים ומוצרי יסוד',
    name: 'מלח אישי',
    description: "1000 יח'",
    price: 19.8,
  },
  {
    id: 208,
    category: 'תבלינים ומוצרי יסוד',
    name: 'פלפל שחור אישי',
    description: "500 יח'",
    price: 25.9,
  },
  {
    id: 209,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכרזית פטריה אישי',
    description: "300 יח'",
    price: 7.7,
  },
  {
    id: 210,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכר מקלות אישי',
    description: "1000 יח'",
    price: 32,
  },
  {
    id: 211,
    category: 'תבלינים ומוצרי יסוד',
    name: 'תבלין לפיצה אישי',
    description: "2000 יח'",
    price: 140,
  },
  {
    id: 212,
    category: 'תבלינים ומוצרי יסוד',
    name: 'תבלין צילי אורגנו אישי',
    description: "1000 יח'",
    price: 112,
  },
  {
    id: 213,
    category: 'תבלינים ומוצרי יסוד',
    name: 'סוכרזית פטנט אישי',
    description: "700 יח'",
    price: 16,
  },
  {
    id: 214,
    category: 'מזון',
    name: 'עוגת אחווה',
    description: 'יחידה',
    price: 7.9,
  },
  {
    id: 215,
    category: 'מזון',
    name: 'טסטר צוייס',
    description: '200 גרם',
    price: '',
  },
  {
    id: 216,
    category: 'מזון',
    name: 'קפה נמס',
    description: '200 גרם',
    price: '',
  },
  {
    id: 217,
    category: 'מזון',
    name: 'קפה טורקי',
    description: '1 קילו',
    price: 39,
  },
  {
    id: 218,
    category: 'מזון',
    name: 'קפה טורקי',
    description: '200 גרם',
    price: '',
  },
  {
    id: 219,
    category: 'מזון',
    name: 'קפה טורקי',
    description: '100 גרם',
    price: '',
  },
  {
    id: 220,
    category: 'מזון',
    name: 'פתיבר',
    description: '1.8 קילו',
    price: 25.6,
  },
  {
    id: 221,
    category: 'מזון',
    name: 'פסטה אוסם',
    description: '500 גרם',
    price: '',
  },
  {
    id: 222,
    category: 'מזון',
    name: 'ספגטי אוסם',
    description: '500 גרם',
    price: '',
  },
  {
    id: 223,
    category: 'מזון',
    name: 'מיונז',
    description: '500 גרם',
    price: '',
  },
  {
    id: 224,
    category: 'מזון',
    name: 'מיונז',
    description: '1 קילו',
    price: '',
  },
  {
    id: 225,
    category: 'מזון',
    name: 'אבקת מרק עוף זך',
    description: '1 קילו',
    price: 17,
  },
  {
    id: 226,
    category: 'מזון',
    name: 'שוקולית',
    description: '1 קילו',
    price: '',
  },
  {
    id: 227,
    category: 'מזון',
    name: 'חלבה בלוק',
    description: '500 גרם',
    price: 9.1,
  },
  {
    id: 228,
    category: 'מזון',
    name: 'חלבה לייט מגש',
    description: '400 גרם',
    price: 12.7,
  },
  {
    id: 229,
    category: 'מזון',
    name: 'חטיף חלבה',
    description: '100 גרם',
    price: 1.7,
  },
  {
    id: 230,
    category: 'מזון',
    name: 'ריבה ויטה',
    description: '680 גרם',
    price: 9.3,
  },
  {
    id: 231,
    category: 'מזון',
    name: 'קונפיטורה 778',
    description: 'רגיל',
    price: 14.4,
  },
  {
    id: 232,
    category: 'מזון',
    name: 'קונפיטורה 779',
    description: 'לייט',
    price: 14.4,
  },
  {
    id: 233,
    category: 'מזון',
    name: 'קקאו',
    description: '150 גרם עלית',
    price: '',
  },
  {
    id: 234,
    category: 'מזון',
    name: 'קקאו ר.ס',
    description: '100 גרם',
    price: 5.5,
  },
  {
    id: 235,
    category: 'מזון',
    name: 'קקאו ר.ס',
    description: 500,
    price: 21,
  },
  {
    id: 236,
    category: 'מזון',
    name: 'קקאו ר.ס',
    description: '1 קילו',
    price: 40,
  },
  {
    id: 237,
    category: 'מזון',
    name: 'תה ירוק ויסוצקי',
    description: "100 יח'",
    price: '',
  },
  {
    id: 238,
    category: 'מזון',
    name: 'תה ירוק ויסוצקי',
    description: "250 יח'",
    price: '',
  },
  {
    id: 239,
    category: 'מזון',
    name: 'תה ירוק ליפטון',
    description: "100 יח'",
    price: '',
  },
  {
    id: 240,
    category: 'מזון',
    name: 'תה ירוק ליפטון',
    description: "25 יח'",
    price: '',
  },
  {
    id: 241,
    category: 'מזון',
    name: 'תה צמחים',
    description: "250 יח'",
    price: '',
  },
  {
    id: 242,
    category: 'מזון',
    name: 'ארל גריי',
    description: "100 יח'",
    price: '',
  },
  {
    id: 243,
    category: 'מזון',
    name: 'מים',
    description: 'שישיה',
    price: '',
  },
  {
    id: 244,
    category: 'מזון',
    name: 'שלוקים',
    description: '1/60.',
    price: 11,
  },
  {
    id: 245,
    category: 'מזון',
    name: 'שלוקים',
    description: '1/8.',
    price: 3.7,
  },
  {
    id: 246,
    category: 'מזון',
    name: 'טרופית',
    description: '1/40.',
    price: 20,
  },
  {
    id: 247,
    category: 'מזון',
    name: 'קוקוס',
    description: '1 קילו',
    price: 21,
  },
  {
    id: 248,
    category: 'מזון',
    name: 'שומשום',
    description: '1 קילו',
    price: 18,
  },
  {
    id: 249,
    category: 'מזון',
    name: 'פסטה',
    description: '10 קילו',
    price: '',
  },
  {
    id: 250,
    category: 'מזון',
    name: 'רוטב אלף איים',
    description: '5 קילו',
    price: '',
  },
  {
    id: 251,
    category: 'מזון',
    name: 'רוטב שום',
    description: '4 קילו',
    price: '',
  },
  {
    id: 252,
    category: 'מזון',
    name: 'עוגיות פילאס',
    description: '600 גרם',
    price: 12,
  },
  {
    id: 253,
    category: 'מזון',
    name: 'עוגיות פילאס',
    description: 'לייט / 350 גרם',
    price: 7.9,
  },
  {
    id: 254,
    category: 'מזון',
    name: 'פריחונים',
    description: '',
    price: 3.5,
  },
  {
    id: 255,
    category: 'מזון',
    name: 'טחינה מתובלת',
    description: '500 גרם',
    price: 11,
  },
  {
    id: 256,
    category: 'מזון',
    name: 'טחינה מתובלת',
    description: '1 קילו',
    price: 18,
  },
  {
    id: 257,
    category: 'מזון',
    name: 'טחינה שומשום מלא',
    description: '500 גרם',
    price: 11,
  },
  {
    id: 258,
    category: 'מזון',
    name: 'קטשופ אוסם',
    description: '750 גרם',
    price: '',
  },
  {
    id: 259,
    category: 'מוצרי חלב',
    name: 'חלב 1 אחוז',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 260,
    category: 'מוצרי חלב',
    name: 'חלב 3 אחוז',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 261,
    category: 'מוצרי חלב',
    name: 'חלב סויה',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 262,
    category: 'מוצרי חלב',
    name: 'חלב לייט',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 263,
    category: 'מוצרי חלב',
    name: 'חלב שיבולית שועל',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 264,
    category: 'מוצרי חלב',
    name: 'חלב וניל',
    description: '1 ליטר',
    price: '',
  },
  {
    id: 265,
    category: 'מוצרי חלב',
    name: 'גבינה לבנה 5%',
    description: '250 גרם',
    price: '',
  },
  {
    id: 266,
    category: 'מוצרי חלב',
    name: 'גבינה לבנה 5%',
    description: '500 גרם',
    price: '',
  },
  {
    id: 267,
    category: 'מוצרי חלב',
    name: 'גבינה לבנה 5%',
    description: '850 גרם',
    price: '',
  },
  {
    id: 268,
    category: 'מוצרי חלב',
    name: 'קוטז 5%',
    description: '250 גרם',
    price: '',
  },
  {
    id: 269,
    category: 'מוצרי חלב',
    name: 'גבינה צהובה גלבוע',
    description: '200 גרם',
    price: '',
  },
  {
    id: 270,
    category: 'מוצרי חלב',
    name: 'גבינה צהובה גלבוע',
    description: '400 גרם',
    price: '',
  },
  {
    id: 271,
    category: 'מוצרי חלב',
    name: 'גבינה צהובה עמק',
    description: '400 גרם',
    price: '',
  },
  {
    id: 272,
    category: 'מוצרי חלב',
    name: 'חמאה',
    description: '100 גרם',
    price: '',
  },
  {
    id: 273,
    category: 'מוצרי חלב',
    name: 'חמאה',
    description: '250 גרם',
    price: '',
  },
  {
    id: 274,
    category: 'מוצרי חלב',
    name: 'מזולה',
    description: '250 גרם',
    price: '',
  },
  {
    id: 275,
    category: 'מוצרי חלב',
    name: 'בלובנד',
    description: '250 גרם',
    price: '',
  },
];

// inventory = _.uniqBy(inventory, 'name')
const sortedInventory = _.sortBy(inventory, 'category');
const c = inventory.map((item) => item.category);

export const categories = _.uniq(c);
export default sortedInventory;

// console.log(inventory)
// console.log(categories)
